// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Common/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event int32

const (
	Event_EVENT_MSG_INFO         Event = 0
	Event_EVENT_REGISTER_REQ     Event = 1
	Event_EVENT_REGISTER_REP     Event = 2
	Event_EVENT_LOGIN_REQ        Event = 3
	Event_EVENT_LOGIN_REP        Event = 4
	Event_EVENT_ADD_ONE_INFO     Event = 5
	Event_EVENT_QUERY_INFO_REQ   Event = 6
	Event_EVENT_RETURN_INFO_LIST Event = 7
	Event_EVENT_CHANGE_INFO_REQ  Event = 8
	Event_EVENT_CHANGE_INFO_REP  Event = 9
	Event_EVENT_DEL_INFO_REQ     Event = 10
	Event_EVENT_DEL_INFO_REP     Event = 11
)

var Event_name = map[int32]string{
	0:  "EVENT_MSG_INFO",
	1:  "EVENT_REGISTER_REQ",
	2:  "EVENT_REGISTER_REP",
	3:  "EVENT_LOGIN_REQ",
	4:  "EVENT_LOGIN_REP",
	5:  "EVENT_ADD_ONE_INFO",
	6:  "EVENT_QUERY_INFO_REQ",
	7:  "EVENT_RETURN_INFO_LIST",
	8:  "EVENT_CHANGE_INFO_REQ",
	9:  "EVENT_CHANGE_INFO_REP",
	10: "EVENT_DEL_INFO_REQ",
	11: "EVENT_DEL_INFO_REP",
}

var Event_value = map[string]int32{
	"EVENT_MSG_INFO":         0,
	"EVENT_REGISTER_REQ":     1,
	"EVENT_REGISTER_REP":     2,
	"EVENT_LOGIN_REQ":        3,
	"EVENT_LOGIN_REP":        4,
	"EVENT_ADD_ONE_INFO":     5,
	"EVENT_QUERY_INFO_REQ":   6,
	"EVENT_RETURN_INFO_LIST": 7,
	"EVENT_CHANGE_INFO_REQ":  8,
	"EVENT_CHANGE_INFO_REP":  9,
	"EVENT_DEL_INFO_REQ":     10,
	"EVENT_DEL_INFO_REP":     11,
}

func (x Event) String() string {
	return proto.EnumName(Event_name, int32(x))
}

func (Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

// 枚举的第一个字段必须为0
type CodeType int32

const (
	CodeType_ERR CodeType = 0
	CodeType_SUC CodeType = 1
)

var CodeType_name = map[int32]string{
	0: "ERR",
	1: "SUC",
}

var CodeType_value = map[string]int32{
	"ERR": 0,
	"SUC": 1,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

type Code struct {
	Code                 CodeType `protobuf:"varint,1,opt,name=code,proto3,enum=CodeType" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_ERR
}

func (m *Code) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Info struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Usetype              string   `protobuf:"bytes,3,opt,name=usetype,proto3" json:"usetype,omitempty"`
	Val                  float32  `protobuf:"fixed32,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Info) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Info) GetUsetype() string {
	if m != nil {
		return m.Usetype
	}
	return ""
}

func (m *Info) GetVal() float32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterEnum("Event", Event_name, Event_value)
	proto.RegisterEnum("CodeType", CodeType_name, CodeType_value)
	proto.RegisterType((*Code)(nil), "Code")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Info)(nil), "Info")
}

func init() {
	proto.RegisterFile("Common/msg.proto", fileDescriptor_ea6b1f2ffa71fb5f)
}

var fileDescriptor_ea6b1f2ffa71fb5f = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x6b, 0xe2, 0x50,
	0x14, 0x86, 0xcd, 0x97, 0x1f, 0x67, 0xc0, 0xb9, 0x9c, 0x99, 0x91, 0x4c, 0x69, 0x41, 0x5c, 0x89,
	0x0b, 0x0b, 0xed, 0xa2, 0x9b, 0x6e, 0x24, 0xde, 0xa6, 0x01, 0x1b, 0xe3, 0x4d, 0x22, 0x74, 0x15,
	0x6c, 0x73, 0x2b, 0x42, 0xf3, 0x81, 0x49, 0x15, 0x7f, 0x52, 0xff, 0x65, 0xc9, 0xbd, 0x4a, 0x16,
	0xb5, 0xbb, 0x37, 0xcf, 0x39, 0xcf, 0x7b, 0x02, 0x09, 0x10, 0x2b, 0x4b, 0x92, 0x2c, 0xbd, 0x4e,
	0x8a, 0xf5, 0x38, 0xdf, 0x66, 0x65, 0x36, 0xb8, 0x03, 0xdd, 0xca, 0x62, 0x8e, 0x57, 0xa0, 0xbf,
	0x66, 0x31, 0x37, 0x95, 0xbe, 0x32, 0xec, 0xde, 0x74, 0xc6, 0x15, 0x0c, 0x0e, 0x39, 0x67, 0x02,
	0x23, 0x01, 0x2d, 0x29, 0xd6, 0xa6, 0xda, 0x57, 0x86, 0x1d, 0x56, 0xc5, 0xc1, 0x3d, 0xe8, 0x61,
	0xc1, 0xb7, 0xd8, 0x05, 0x75, 0x13, 0x0b, 0xcd, 0x60, 0xea, 0x26, 0x46, 0x04, 0x3d, 0x5d, 0x25,
	0xfc, 0xb8, 0x2a, 0x72, 0x65, 0xe7, 0xfb, 0xd8, 0xd4, 0xa4, 0x9d, 0xef, 0xe3, 0xc1, 0x12, 0x74,
	0x27, 0x7d, 0xcb, 0xce, 0xd9, 0xe5, 0xe6, 0x68, 0x1b, 0x4c, 0x64, 0x34, 0xa1, 0xf5, 0x51, 0xf0,
	0xf2, 0x90, 0xf3, 0x63, 0xc3, 0xe9, 0xb1, 0xea, 0xdd, 0xad, 0xde, 0x4d, 0xbd, 0xaf, 0x0c, 0x55,
	0x56, 0xc5, 0xd1, 0xa7, 0x0a, 0x06, 0xdd, 0xf1, 0xb4, 0x44, 0x84, 0x2e, 0x5d, 0x52, 0x37, 0x88,
	0x9e, 0x7c, 0x3b, 0x72, 0xdc, 0x87, 0x39, 0x69, 0x60, 0x0f, 0x50, 0x32, 0x46, 0x6d, 0xc7, 0x0f,
	0x28, 0x8b, 0x18, 0x5d, 0x10, 0xe5, 0x2c, 0xf7, 0x88, 0x8a, 0x7f, 0xe0, 0xb7, 0xe4, 0xb3, 0xb9,
	0xed, 0xb8, 0x62, 0x59, 0xfb, 0x0e, 0x3d, 0xa2, 0xd7, 0x0d, 0x93, 0xe9, 0x34, 0x9a, 0xbb, 0x54,
	0x5e, 0x34, 0xd0, 0x84, 0xbf, 0x92, 0x2f, 0x42, 0xca, 0x9e, 0x05, 0x15, 0x35, 0x4d, 0xbc, 0x80,
	0xde, 0xe9, 0x66, 0x10, 0x32, 0x57, 0x8e, 0x66, 0x8e, 0x1f, 0x90, 0x16, 0xfe, 0x87, 0x7f, 0x72,
	0x66, 0x3d, 0x4e, 0x5c, 0x9b, 0xd6, 0x5a, 0xfb, 0xa7, 0x91, 0x47, 0x3a, 0xf5, 0x3b, 0x4c, 0xe9,
	0xac, 0x56, 0xe0, 0x2c, 0xf7, 0xc8, 0xaf, 0xd1, 0x25, 0xb4, 0x4f, 0x5f, 0x19, 0x5b, 0xa0, 0x51,
	0xc6, 0x48, 0xa3, 0x0a, 0x7e, 0x68, 0x11, 0xe5, 0xa5, 0x29, 0xfe, 0x8f, 0xdb, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4e, 0xb0, 0xa5, 0x78, 0x33, 0x02, 0x00, 0x00,
}
