// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Common/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event int32

const (
	Event_EVENT_MSG_INFO     Event = 0
	Event_EVENT_REGISTER_REQ Event = 1
	Event_EVENT_REGISTER_REP Event = 2
	Event_EVENT_LOGIN_REQ    Event = 3
	Event_EVENT_LOGIN_REP    Event = 4
	Event_EVENT_ADD_ONE_INFO Event = 5
)

var Event_name = map[int32]string{
	0: "EVENT_MSG_INFO",
	1: "EVENT_REGISTER_REQ",
	2: "EVENT_REGISTER_REP",
	3: "EVENT_LOGIN_REQ",
	4: "EVENT_LOGIN_REP",
	5: "EVENT_ADD_ONE_INFO",
}

var Event_value = map[string]int32{
	"EVENT_MSG_INFO":     0,
	"EVENT_REGISTER_REQ": 1,
	"EVENT_REGISTER_REP": 2,
	"EVENT_LOGIN_REQ":    3,
	"EVENT_LOGIN_REP":    4,
	"EVENT_ADD_ONE_INFO": 5,
}

func (x Event) String() string {
	return proto.EnumName(Event_name, int32(x))
}

func (Event) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

// 枚举的第一个字段必须为0
type CodeType int32

const (
	CodeType_ERR CodeType = 0
	CodeType_SUC CodeType = 1
)

var CodeType_name = map[int32]string{
	0: "ERR",
	1: "SUC",
}

var CodeType_value = map[string]int32{
	"ERR": 0,
	"SUC": 1,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

type Code struct {
	Code                 CodeType `protobuf:"varint,1,opt,name=code,proto3,enum=CodeType" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{0}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_ERR
}

func (m *Code) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Info struct {
	Userid               int32    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Usetype              string   `protobuf:"bytes,3,opt,name=usetype,proto3" json:"usetype,omitempty"`
	Val                  int32    `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b1f2ffa71fb5f, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *Info) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Info) GetUsetype() string {
	if m != nil {
		return m.Usetype
	}
	return ""
}

func (m *Info) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterEnum("Event", Event_name, Event_value)
	proto.RegisterEnum("CodeType", CodeType_name, CodeType_value)
	proto.RegisterType((*Code)(nil), "Code")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Info)(nil), "Info")
}

func init() {
	proto.RegisterFile("Common/msg.proto", fileDescriptor_ea6b1f2ffa71fb5f)
}

var fileDescriptor_ea6b1f2ffa71fb5f = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x99, 0x76, 0x0a, 0x3f, 0x77, 0xc1, 0x3f, 0xb9, 0x26, 0xa4, 0x0b, 0x4d, 0x08, 0x2b,
	0xc2, 0x02, 0x13, 0x5d, 0xb8, 0x71, 0x63, 0x60, 0x24, 0x4d, 0xb4, 0xe0, 0x50, 0x5c, 0xda, 0xa0,
	0x33, 0x92, 0x26, 0xb6, 0xd3, 0xb4, 0x05, 0xc2, 0x43, 0xf8, 0xce, 0x66, 0xa6, 0x45, 0x17, 0xba,
	0x3b, 0xf7, 0xcb, 0x39, 0x5f, 0x93, 0x0e, 0xb0, 0xa9, 0x4e, 0x53, 0x9d, 0x5d, 0xa6, 0xe5, 0x76,
	0x92, 0x17, 0xba, 0xd2, 0xc3, 0x1b, 0xa0, 0x53, 0x2d, 0x15, 0x5e, 0x00, 0x7d, 0xd3, 0x52, 0xf9,
	0x64, 0x40, 0x46, 0xbd, 0xab, 0xee, 0xc4, 0xc0, 0xe8, 0x98, 0x2b, 0x61, 0x31, 0x32, 0x70, 0xd3,
	0x72, 0xeb, 0x3b, 0x03, 0x32, 0xea, 0x0a, 0x13, 0x87, 0xb7, 0x40, 0xd7, 0xa5, 0x2a, 0xb0, 0x07,
	0x4e, 0x22, 0xed, 0xcc, 0x13, 0x4e, 0x22, 0x11, 0x81, 0x66, 0x9b, 0x54, 0x35, 0x55, 0x9b, 0xcd,
	0x3a, 0x3f, 0x48, 0xdf, 0xad, 0xd7, 0xf9, 0x41, 0x0e, 0x5f, 0x80, 0x06, 0xd9, 0xbb, 0xc6, 0x3e,
	0xb4, 0x77, 0xa5, 0x2a, 0xbe, 0x0d, 0xcd, 0x65, 0x2c, 0x55, 0xd2, 0x58, 0x3c, 0x61, 0x33, 0xfa,
	0xd0, 0xd9, 0x95, 0xaa, 0x3a, 0xe6, 0xaa, 0x31, 0x9d, 0x4e, 0xe3, 0xdf, 0x6f, 0x3e, 0x7c, 0x6a,
	0xcb, 0x26, 0x8e, 0x3f, 0x09, 0x78, 0x7c, 0xaf, 0xb2, 0x0a, 0x11, 0x7a, 0xfc, 0x99, 0x87, 0x51,
	0xfc, 0xb8, 0x9a, 0xc7, 0x41, 0x78, 0xbf, 0x60, 0x2d, 0xec, 0x03, 0xd6, 0x4c, 0xf0, 0x79, 0xb0,
	0x8a, 0xb8, 0x88, 0x05, 0x7f, 0x62, 0xe4, 0x4f, 0xbe, 0x64, 0x0e, 0x9e, 0xc1, 0xff, 0x9a, 0x3f,
	0x2c, 0xe6, 0x41, 0x68, 0xcb, 0xee, 0x6f, 0xb8, 0x64, 0xf4, 0xc7, 0x70, 0x37, 0x9b, 0xc5, 0x8b,
	0x90, 0xd7, 0x5f, 0xf4, 0xc6, 0xe7, 0xf0, 0xef, 0xf4, 0x47, 0xb1, 0x03, 0x2e, 0x17, 0x82, 0xb5,
	0x4c, 0x58, 0xad, 0xa7, 0x8c, 0xbc, 0xb6, 0xed, 0x5b, 0x5c, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x73, 0xb7, 0xd5, 0xd5, 0x9f, 0x01, 0x00, 0x00,
}
