// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JiZhangBo/jiZhangBo.proto

package jiZhangBo

import (
	Common "Common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SelectInfo struct {
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// repeated表示可重复
	// 表示有多个Info
	Infolist             []*Common.Info `protobuf:"bytes,3,rep,name=infolist,proto3" json:"infolist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SelectInfo) Reset()         { *m = SelectInfo{} }
func (m *SelectInfo) String() string { return proto.CompactTextString(m) }
func (*SelectInfo) ProtoMessage()    {}
func (*SelectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{0}
}

func (m *SelectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectInfo.Unmarshal(m, b)
}
func (m *SelectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectInfo.Marshal(b, m, deterministic)
}
func (m *SelectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectInfo.Merge(m, src)
}
func (m *SelectInfo) XXX_Size() int {
	return xxx_messageInfo_SelectInfo.Size(m)
}
func (m *SelectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SelectInfo proto.InternalMessageInfo

func (m *SelectInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SelectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SelectInfo) GetInfolist() []*Common.Info {
	if m != nil {
		return m.Infolist
	}
	return nil
}

type AddInfo struct {
	Info                 *Common.Info `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddInfo) Reset()         { *m = AddInfo{} }
func (m *AddInfo) String() string { return proto.CompactTextString(m) }
func (*AddInfo) ProtoMessage()    {}
func (*AddInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2451c90a91c96d3a, []int{1}
}

func (m *AddInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInfo.Unmarshal(m, b)
}
func (m *AddInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInfo.Marshal(b, m, deterministic)
}
func (m *AddInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInfo.Merge(m, src)
}
func (m *AddInfo) XXX_Size() int {
	return xxx_messageInfo_AddInfo.Size(m)
}
func (m *AddInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddInfo proto.InternalMessageInfo

func (m *AddInfo) GetInfo() *Common.Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*SelectInfo)(nil), "SelectInfo")
	proto.RegisterType((*AddInfo)(nil), "AddInfo")
}

func init() {
	proto.RegisterFile("JiZhangBo/jiZhangBo.proto", fileDescriptor_2451c90a91c96d3a)
}

var fileDescriptor_2451c90a91c96d3a = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xf4, 0xca, 0x8c, 0xca,
	0x48, 0xcc, 0x4b, 0x77, 0xca, 0xd7, 0xcf, 0x82, 0xb1, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0xa5,
	0x04, 0x9c, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0xf4, 0x73, 0x8b, 0xd3, 0x21, 0x22, 0x4a, 0xc1, 0x5c,
	0x5c, 0xc1, 0xa9, 0x39, 0xa9, 0xc9, 0x25, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x22, 0x17, 0x47,
	0x66, 0x5e, 0x5a, 0x7e, 0x4e, 0x66, 0x71, 0x89, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0xab,
	0x1e, 0x48, 0x73, 0x10, 0x5c, 0x58, 0x49, 0x85, 0x8b, 0xdd, 0x31, 0x25, 0x05, 0x6c, 0xa2, 0x24,
	0x17, 0x0b, 0x48, 0x18, 0x6c, 0x26, 0x5c, 0x25, 0x58, 0x28, 0x89, 0x0d, 0xec, 0x02, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x86, 0x6a, 0x79, 0xb0, 0x00, 0x00, 0x00,
}
