// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 枚举的第一个字段必须为0
type CodeType int32

const (
	CodeType_ERR CodeType = 0
	CodeType_SUC CodeType = 1
)

var CodeType_name = map[int32]string{
	0: "ERR",
	1: "SUC",
}

var CodeType_value = map[string]int32{
	"ERR": 0,
	"SUC": 1,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type Code struct {
	Code                 CodeType `protobuf:"varint,1,opt,name=code,proto3,enum=CodeType" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (m *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(m, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_ERR
}

func (m *Code) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Info struct {
	Userid               int32    `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Time                 int32    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Usetype              string   `protobuf:"bytes,3,opt,name=usetype,proto3" json:"usetype,omitempty"`
	Val                  int32    `protobuf:"varint,4,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetUserid() int32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *Info) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Info) GetUsetype() string {
	if m != nil {
		return m.Usetype
	}
	return ""
}

func (m *Info) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

type SelectInfo struct {
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// repeated表示可重复
	// 表示有多个Info
	Infolist             []*Info  `protobuf:"bytes,3,rep,name=infolist,proto3" json:"infolist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectInfo) Reset()         { *m = SelectInfo{} }
func (m *SelectInfo) String() string { return proto.CompactTextString(m) }
func (*SelectInfo) ProtoMessage()    {}
func (*SelectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *SelectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectInfo.Unmarshal(m, b)
}
func (m *SelectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectInfo.Marshal(b, m, deterministic)
}
func (m *SelectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectInfo.Merge(m, src)
}
func (m *SelectInfo) XXX_Size() int {
	return xxx_messageInfo_SelectInfo.Size(m)
}
func (m *SelectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SelectInfo proto.InternalMessageInfo

func (m *SelectInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SelectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SelectInfo) GetInfolist() []*Info {
	if m != nil {
		return m.Infolist
	}
	return nil
}

func init() {
	proto.RegisterEnum("CodeType", CodeType_name, CodeType_value)
	proto.RegisterType((*Code)(nil), "Code")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Info)(nil), "Info")
	proto.RegisterType((*SelectInfo)(nil), "SelectInfo")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0x6b, 0x4b, 0x4e, 0xe2, 0x2b, 0x04, 0x73, 0x43, 0xd1, 0xd0, 0x82, 0xeb, 0xc9, 0x64,
	0xf0, 0x90, 0x0e, 0x7d, 0x80, 0xd0, 0xa1, 0xab, 0xdc, 0xac, 0x85, 0x34, 0xba, 0x04, 0x81, 0x6d,
	0x19, 0x4b, 0x29, 0xe4, 0xed, 0x8b, 0x0e, 0x27, 0x73, 0xb7, 0xef, 0x7e, 0xfe, 0x4f, 0x3a, 0x0e,
	0xf2, 0xde, 0x9f, 0x9b, 0x71, 0x72, 0xc1, 0x55, 0xef, 0x20, 0x77, 0xce, 0x10, 0xbe, 0x80, 0x3c,
	0x3a, 0x43, 0x2a, 0x29, 0x93, 0x7a, 0xbd, 0xcd, 0x9b, 0x18, 0x7e, 0x5d, 0x47, 0xd2, 0x1c, 0x63,
	0x01, 0xa2, 0xf7, 0x67, 0x95, 0x96, 0x49, 0x9d, 0xeb, 0x88, 0xd5, 0x06, 0xe4, 0xde, 0xd3, 0x84,
	0x6b, 0x48, 0xad, 0x61, 0x2d, 0xd3, 0xa9, 0x35, 0x88, 0x20, 0x87, 0x43, 0x4f, 0x73, 0x95, 0xb9,
	0xfa, 0x06, 0xf9, 0x39, 0x9c, 0x1c, 0x3e, 0xc1, 0xe2, 0xe2, 0x69, 0xba, 0xf7, 0xe7, 0x29, 0x3a,
	0xc1, 0xce, 0x4e, 0xa6, 0x99, 0x51, 0xc1, 0xf2, 0xe2, 0x29, 0x5c, 0x47, 0x52, 0x82, 0x9f, 0xba,
	0x8d, 0x71, 0x97, 0xdf, 0x43, 0xa7, 0x24, 0x97, 0x23, 0x56, 0x2d, 0x40, 0x4b, 0x1d, 0x1d, 0x03,
	0xff, 0xf2, 0x8f, 0x8d, 0xf0, 0x15, 0x56, 0x76, 0x38, 0xb9, 0xce, 0xfa, 0xa0, 0x44, 0x29, 0xea,
	0xc7, 0x6d, 0xd6, 0x44, 0x59, 0xdf, 0xe3, 0xcd, 0x33, 0xac, 0x6e, 0x47, 0xc0, 0x25, 0x88, 0x0f,
	0xad, 0x8b, 0x87, 0x08, 0xed, 0x7e, 0x57, 0x24, 0x3f, 0x0b, 0x3e, 0xdf, 0xdb, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0xfe, 0x57, 0xc1, 0x4b, 0x01, 0x00, 0x00,
}
